package com.selenium.enums;

public enum ConfigProperties {
	
	URL,
	OVERRIDEREPORTS,
	PASSEDSTEPSCREENSHOTS,
	FAILEDSTEPSCREENSHOTS,
	SKIPSTEPSCREENSHOTS,
	RETRYFAILEDTESTS,
	RUNMODE, 
	SELENIUMGRIDURL,
	SELENIUMGRIDAWSURL,
	SENDRESULTTOELK,
	ELASTICURL,
	BROWSER,

}
